Name=input("enter your name")
Branch=input("enter your branch")
Gender=input("enter your gender")
College=input("enter your college")
Age=input("enter your age")
print(Name)
print(Branch)
print(Gender)
print(College)
